[2019-02-17 18:49:14,755: INFO/MainProcess] Connected to redis://127.0.0.1:6379/8
[2019-02-17 18:49:14,764: INFO/MainProcess] mingle: searching for neighbors
[2019-02-17 18:49:15,783: INFO/MainProcess] mingle: all alone
[2019-02-17 18:49:15,793: WARNING/MainProcess] /home/ubuntu/.virtualenvs/django_py3/lib/python3.5/site-packages/celery/fixups/django.py:200: UserWarning: Using settings.DEBUG leads to a memory leak, never use this setting in production environments!
  warnings.warn('Using settings.DEBUG leads to a memory leak, never '

[2019-02-17 18:49:15,793: INFO/MainProcess] w1@VM-0-11-ubuntu ready.
[2019-02-17 18:51:42,710: INFO/MainProcess] Received task: celery_tasks.tasks.generate_static_index_html[2b5072d2-898c-4874-ad45-58effd570046]  
[2019-02-17 18:51:42,744: WARNING/ForkPoolWorker-1] /home/ubuntu/.virtualenvs/django_py3/lib/python3.5/site-packages/haystack/backends/whoosh_cn_backend.py:9: RemovedInDjango19Warning: The utilities in django.db.models.loading are deprecated in favor of the new application loading system.
  from django.db.models.loading import get_model

[2019-02-17 18:51:43,057: INFO/ForkPoolWorker-1] Task celery_tasks.tasks.generate_static_index_html[2b5072d2-898c-4874-ad45-58effd570046] succeeded in 0.34500326501438394s: None
[2019-02-17 18:59:07,426: INFO/MainProcess] Received task: celery_tasks.tasks.send_register_active_email[473ff7f4-78e2-4751-987d-246385263aa0]  
[2019-02-17 19:07:35,915: INFO/MainProcess] Received task: celery_tasks.tasks.send_register_active_email[9926178e-3425-4bd7-b30f-3ef4f75bbf8c]  
[2019-02-17 19:16:05,483: ERROR/ForkPoolWorker-1] Task celery_tasks.tasks.send_register_active_email[473ff7f4-78e2-4751-987d-246385263aa0] raised unexpected: TimeoutError(110, 'Connection timed out')
Traceback (most recent call last):
  File "/home/ubuntu/.virtualenvs/django_py3/lib/python3.5/site-packages/celery/app/trace.py", line 382, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/home/ubuntu/.virtualenvs/django_py3/lib/python3.5/site-packages/celery/app/trace.py", line 641, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/ubuntu/django/dailyfresh/celery_tasks/tasks.py", line 32, in send_register_active_email
    send_mail(subject, message, sender, receiver, html_message=html_message)
  File "/home/ubuntu/.virtualenvs/django_py3/lib/python3.5/site-packages/django/core/mail/__init__.py", line 62, in send_mail
    return mail.send()
  File "/home/ubuntu/.virtualenvs/django_py3/lib/python3.5/site-packages/django/core/mail/message.py", line 303, in send
    return self.get_connection(fail_silently).send_messages([self])
  File "/home/ubuntu/.virtualenvs/django_py3/lib/python3.5/site-packages/django/core/mail/backends/smtp.py", line 100, in send_messages
    new_conn_created = self.open()
  File "/home/ubuntu/.virtualenvs/django_py3/lib/python3.5/site-packages/django/core/mail/backends/smtp.py", line 58, in open
    self.connection = connection_class(self.host, self.port, **connection_params)
  File "/usr/lib/python3.5/smtplib.py", line 251, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/lib/python3.5/smtplib.py", line 335, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/lib/python3.5/smtplib.py", line 306, in _get_socket
    self.source_address)
  File "/usr/lib/python3.5/socket.py", line 711, in create_connection
    raise err
  File "/usr/lib/python3.5/socket.py", line 702, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out
[2019-02-17 19:17:47,822: ERROR/MainProcess] Error on stopping Pool: TypeError("can't pickle memoryview objects",)
Traceback (most recent call last):
  File "/home/ubuntu/.virtualenvs/django_py3/lib/python3.5/site-packages/celery/worker/worker.py", line 205, in start
    self.blueprint.start(self)
  File "/home/ubuntu/.virtualenvs/django_py3/lib/python3.5/site-packages/celery/bootsteps.py", line 119, in start
    step.start(parent)
  File "/home/ubuntu/.virtualenvs/django_py3/lib/python3.5/site-packages/celery/bootsteps.py", line 369, in start
    return self.obj.start()
  File "/home/ubuntu/.virtualenvs/django_py3/lib/python3.5/site-packages/celery/worker/consumer/consumer.py", line 317, in start
    blueprint.start(self)
  File "/home/ubuntu/.virtualenvs/django_py3/lib/python3.5/site-packages/celery/bootsteps.py", line 119, in start
    step.start(parent)
  File "/home/ubuntu/.virtualenvs/django_py3/lib/python3.5/site-packages/celery/worker/consumer/consumer.py", line 593, in start
    c.loop(*c.loop_args())
  File "/home/ubuntu/.virtualenvs/django_py3/lib/python3.5/site-packages/celery/worker/loops.py", line 91, in asynloop
    next(loop)
  File "/home/ubuntu/.virtualenvs/django_py3/lib/python3.5/site-packages/kombu/asynchronous/hub.py", line 298, in create_loop
    events = poll(poll_timeout)
  File "/home/ubuntu/.virtualenvs/django_py3/lib/python3.5/site-packages/kombu/utils/eventio.py", line 84, in poll
    return self._epoll.poll(timeout if timeout is not None else -1)
  File "/home/ubuntu/.virtualenvs/django_py3/lib/python3.5/site-packages/celery/apps/worker.py", line 284, in _handle_request
    raise exc(exitcode)
celery.exceptions.WorkerShutdown: 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/.virtualenvs/django_py3/lib/python3.5/site-packages/celery/bootsteps.py", line 151, in send_all
    fun(parent, *args)
  File "/home/ubuntu/.virtualenvs/django_py3/lib/python3.5/site-packages/celery/bootsteps.py", line 373, in stop
    return self.obj.stop()
  File "/home/ubuntu/.virtualenvs/django_py3/lib/python3.5/site-packages/celery/concurrency/base.py", line 122, in stop
    self.on_stop()
  File "/home/ubuntu/.virtualenvs/django_py3/lib/python3.5/site-packages/celery/concurrency/prefork.py", line 140, in on_stop
    self._pool.join()
  File "/home/ubuntu/.virtualenvs/django_py3/lib/python3.5/site-packages/billiard/pool.py", line 1578, in join
    stop_if_not_current(self._result_handler)
  File "/home/ubuntu/.virtualenvs/django_py3/lib/python3.5/site-packages/billiard/pool.py", line 143, in stop_if_not_current
    thread.stop(timeout)
  File "/home/ubuntu/.virtualenvs/django_py3/lib/python3.5/site-packages/billiard/pool.py", line 500, in stop
    self.on_stop_not_started()
  File "/home/ubuntu/.virtualenvs/django_py3/lib/python3.5/site-packages/celery/concurrency/asynpool.py", line 332, in on_stop_not_started
    check_timeouts()
  File "/home/ubuntu/.virtualenvs/django_py3/lib/python3.5/site-packages/billiard/pool.py", line 744, in handle_event
    next(self._it)
  File "/home/ubuntu/.virtualenvs/django_py3/lib/python3.5/site-packages/billiard/pool.py", line 697, in handle_timeouts
    cache = copy.deepcopy(self.cache)
  File "/home/ubuntu/.virtualenvs/django_py3/lib/python3.5/copy.py", line 155, in deepcopy
    y = copier(x, memo)
  File "/home/ubuntu/.virtualenvs/django_py3/lib/python3.5/copy.py", line 243, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/ubuntu/.virtualenvs/django_py3/lib/python3.5/copy.py", line 182, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/home/ubuntu/.virtualenvs/django_py3/lib/python3.5/copy.py", line 297, in _reconstruct
    state = deepcopy(state, memo)
  File "/home/ubuntu/.virtualenvs/django_py3/lib/python3.5/copy.py", line 155, in deepcopy
    y = copier(x, memo)
  File "/home/ubuntu/.virtualenvs/django_py3/lib/python3.5/copy.py", line 243, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/ubuntu/.virtualenvs/django_py3/lib/python3.5/copy.py", line 155, in deepcopy
    y = copier(x, memo)
  File "/home/ubuntu/.virtualenvs/django_py3/lib/python3.5/copy.py", line 223, in _deepcopy_tuple
    y = [deepcopy(a, memo) for a in x]
  File "/home/ubuntu/.virtualenvs/django_py3/lib/python3.5/copy.py", line 223, in <listcomp>
    y = [deepcopy(a, memo) for a in x]
  File "/home/ubuntu/.virtualenvs/django_py3/lib/python3.5/copy.py", line 174, in deepcopy
    rv = reductor(4)
TypeError: can't pickle memoryview objects
[2019-02-17 19:17:51,178: INFO/MainProcess] Connected to redis://127.0.0.1:6379/8
[2019-02-17 19:17:51,186: INFO/MainProcess] mingle: searching for neighbors
[2019-02-17 19:17:52,205: INFO/MainProcess] mingle: all alone
[2019-02-17 19:17:52,212: WARNING/MainProcess] /home/ubuntu/.virtualenvs/django_py3/lib/python3.5/site-packages/celery/fixups/django.py:200: UserWarning: Using settings.DEBUG leads to a memory leak, never use this setting in production environments!
  warnings.warn('Using settings.DEBUG leads to a memory leak, never '

[2019-02-17 19:17:52,212: INFO/MainProcess] w1@VM-0-11-ubuntu ready.
[2019-02-17 19:19:37,660: INFO/MainProcess] Received task: celery_tasks.tasks.send_register_active_email[daa49e2f-6bde-4088-bc9a-6a4271d18e05]  
[2019-02-17 19:36:35,562: ERROR/ForkPoolWorker-1] Task celery_tasks.tasks.send_register_active_email[daa49e2f-6bde-4088-bc9a-6a4271d18e05] raised unexpected: TimeoutError(110, 'Connection timed out')
Traceback (most recent call last):
  File "/home/ubuntu/.virtualenvs/django_py3/lib/python3.5/site-packages/celery/app/trace.py", line 382, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/home/ubuntu/.virtualenvs/django_py3/lib/python3.5/site-packages/celery/app/trace.py", line 641, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/ubuntu/django/dailyfresh/celery_tasks/tasks.py", line 32, in send_register_active_email
    send_mail(subject, message, sender, receiver, html_message=html_message)
  File "/home/ubuntu/.virtualenvs/django_py3/lib/python3.5/site-packages/django/core/mail/__init__.py", line 62, in send_mail
    return mail.send()
  File "/home/ubuntu/.virtualenvs/django_py3/lib/python3.5/site-packages/django/core/mail/message.py", line 303, in send
    return self.get_connection(fail_silently).send_messages([self])
  File "/home/ubuntu/.virtualenvs/django_py3/lib/python3.5/site-packages/django/core/mail/backends/smtp.py", line 100, in send_messages
    new_conn_created = self.open()
  File "/home/ubuntu/.virtualenvs/django_py3/lib/python3.5/site-packages/django/core/mail/backends/smtp.py", line 58, in open
    self.connection = connection_class(self.host, self.port, **connection_params)
  File "/usr/lib/python3.5/smtplib.py", line 251, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/lib/python3.5/smtplib.py", line 335, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/lib/python3.5/smtplib.py", line 306, in _get_socket
    self.source_address)
  File "/usr/lib/python3.5/socket.py", line 711, in create_connection
    raise err
  File "/usr/lib/python3.5/socket.py", line 702, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out
[2019-02-17 19:42:18,279: INFO/MainProcess] Received task: celery_tasks.tasks.send_register_active_email[0cdccec8-51f1-4e90-8303-8f9038c47bfd]  
[2019-02-17 19:42:19,705: INFO/ForkPoolWorker-1] Task celery_tasks.tasks.send_register_active_email[0cdccec8-51f1-4e90-8303-8f9038c47bfd] succeeded in 1.42518589500105s: None
[2019-02-17 19:44:52,466: INFO/MainProcess] Received task: celery_tasks.tasks.send_register_active_email[392fb09f-9dd9-4915-a26e-724340c50c03]  
[2019-02-17 19:44:53,009: INFO/ForkPoolWorker-1] Task celery_tasks.tasks.send_register_active_email[392fb09f-9dd9-4915-a26e-724340c50c03] succeeded in 0.5421802490018308s: None
[2019-02-17 19:46:30,172: INFO/MainProcess] Received task: celery_tasks.tasks.send_register_active_email[a408af25-32f1-4e56-b00c-566f7f83f152]  
[2019-02-17 19:46:30,737: INFO/ForkPoolWorker-1] Task celery_tasks.tasks.send_register_active_email[a408af25-32f1-4e56-b00c-566f7f83f152] succeeded in 0.5633301330381073s: None
[2019-02-17 19:48:49,988: INFO/MainProcess] Received task: celery_tasks.tasks.send_register_active_email[641ef84b-e37d-4fca-9581-63caf894c48b]  
[2019-02-17 19:49:01,848: INFO/ForkPoolWorker-1] Task celery_tasks.tasks.send_register_active_email[641ef84b-e37d-4fca-9581-63caf894c48b] succeeded in 11.859652821964119s: None
[2019-02-17 19:49:48,482: INFO/MainProcess] Connected to redis://127.0.0.1:6379/8
[2019-02-17 19:49:48,489: INFO/MainProcess] mingle: searching for neighbors
[2019-02-17 19:49:49,508: INFO/MainProcess] mingle: all alone
[2019-02-17 19:49:49,516: WARNING/MainProcess] /home/ubuntu/.virtualenvs/django_py3/lib/python3.5/site-packages/celery/fixups/django.py:200: UserWarning: Using settings.DEBUG leads to a memory leak, never use this setting in production environments!
  warnings.warn('Using settings.DEBUG leads to a memory leak, never '

[2019-02-17 19:49:49,516: INFO/MainProcess] w1@VM-0-11-ubuntu ready.
[2019-02-17 20:13:19,232: INFO/MainProcess] Received task: celery_tasks.tasks.send_register_active_email[3be64525-24ca-42ef-89fb-8c76159f3cd6]  
[2019-02-17 20:13:21,305: INFO/ForkPoolWorker-1] Task celery_tasks.tasks.send_register_active_email[3be64525-24ca-42ef-89fb-8c76159f3cd6] succeeded in 2.0718470939900726s: None
[2019-02-18 15:33:47,823: CRITICAL/MainProcess] Unrecoverable error: ResponseError('MISCONF Redis is configured to save RDB snapshots, but is currently not able to persist on disk. Commands that may modify the data set are disabled. Please check Redis logs for details about the error.',)
Traceback (most recent call last):
  File "/home/ubuntu/.virtualenvs/django_py3/lib/python3.5/site-packages/celery/worker/worker.py", line 205, in start
    self.blueprint.start(self)
  File "/home/ubuntu/.virtualenvs/django_py3/lib/python3.5/site-packages/celery/bootsteps.py", line 119, in start
    step.start(parent)
  File "/home/ubuntu/.virtualenvs/django_py3/lib/python3.5/site-packages/celery/bootsteps.py", line 369, in start
    return self.obj.start()
  File "/home/ubuntu/.virtualenvs/django_py3/lib/python3.5/site-packages/celery/worker/consumer/consumer.py", line 317, in start
    blueprint.start(self)
  File "/home/ubuntu/.virtualenvs/django_py3/lib/python3.5/site-packages/celery/bootsteps.py", line 119, in start
    step.start(parent)
  File "/home/ubuntu/.virtualenvs/django_py3/lib/python3.5/site-packages/celery/worker/consumer/consumer.py", line 593, in start
    c.loop(*c.loop_args())
  File "/home/ubuntu/.virtualenvs/django_py3/lib/python3.5/site-packages/celery/worker/loops.py", line 91, in asynloop
    next(loop)
  File "/home/ubuntu/.virtualenvs/django_py3/lib/python3.5/site-packages/kombu/asynchronous/hub.py", line 354, in create_loop
    cb(*cbargs)
  File "/home/ubuntu/.virtualenvs/django_py3/lib/python3.5/site-packages/kombu/transport/redis.py", line 1047, in on_readable
    self.cycle.on_readable(fileno)
  File "/home/ubuntu/.virtualenvs/django_py3/lib/python3.5/site-packages/kombu/transport/redis.py", line 344, in on_readable
    chan.handlers[type]()
  File "/home/ubuntu/.virtualenvs/django_py3/lib/python3.5/site-packages/kombu/transport/redis.py", line 721, in _brpop_read
    **options)
  File "/home/ubuntu/.virtualenvs/django_py3/lib/python3.5/site-packages/redis/client.py", line 680, in parse_response
    response = connection.read_response()
  File "/home/ubuntu/.virtualenvs/django_py3/lib/python3.5/site-packages/redis/connection.py", line 629, in read_response
    raise response
redis.exceptions.ResponseError: MISCONF Redis is configured to save RDB snapshots, but is currently not able to persist on disk. Commands that may modify the data set are disabled. Please check Redis logs for details about the error.
[2019-02-27 18:22:59,170: INFO/MainProcess] Connected to redis://127.0.0.1:6379/8
[2019-02-27 18:22:59,179: INFO/MainProcess] mingle: searching for neighbors
[2019-02-27 18:23:00,197: INFO/MainProcess] mingle: all alone
[2019-02-27 18:23:00,204: INFO/MainProcess] w1@VM-0-11-ubuntu ready.
[2019-02-27 18:24:05,456: INFO/MainProcess] Received task: celery_tasks.tasks.send_register_active_email[cbd7434b-778c-44fd-a958-1fed43769ab2]  
[2019-02-27 18:24:08,175: INFO/ForkPoolWorker-1] Task celery_tasks.tasks.send_register_active_email[cbd7434b-778c-44fd-a958-1fed43769ab2] succeeded in 2.7177982649300247s: None
[2019-02-27 18:39:30,862: INFO/MainProcess] Received task: celery_tasks.tasks.send_register_active_email[b17b53de-a483-4c6f-81fd-4c12d7e96ac3]  
[2019-02-27 18:39:32,509: INFO/ForkPoolWorker-1] Task celery_tasks.tasks.send_register_active_email[b17b53de-a483-4c6f-81fd-4c12d7e96ac3] succeeded in 1.6462548759300262s: None
[2019-02-27 18:41:03,703: INFO/MainProcess] Connected to redis://127.0.0.1:6379/8
[2019-02-27 18:41:03,711: INFO/MainProcess] mingle: searching for neighbors
[2019-02-27 18:41:04,730: INFO/MainProcess] mingle: all alone
[2019-02-27 18:41:04,738: INFO/MainProcess] w1@VM-0-11-ubuntu ready.
[2019-02-27 18:41:38,515: INFO/MainProcess] Received task: celery_tasks.tasks.send_register_active_email[4990137e-78bb-4ebf-8ec7-425d188dde98]  
[2019-02-27 18:41:38,955: INFO/ForkPoolWorker-1] Task celery_tasks.tasks.send_register_active_email[4990137e-78bb-4ebf-8ec7-425d188dde98] succeeded in 0.4383909390307963s: None
[2019-02-27 20:29:09,098: INFO/MainProcess] Received task: celery_tasks.tasks.generate_static_index_html[b4dfbe88-8815-41a4-b150-e3cf9e3d6f24]  
[2019-02-27 20:29:09,133: WARNING/ForkPoolWorker-1] /home/ubuntu/.virtualenvs/django_py3/lib/python3.5/site-packages/haystack/backends/whoosh_cn_backend.py:9: RemovedInDjango19Warning: The utilities in django.db.models.loading are deprecated in favor of the new application loading system.
  from django.db.models.loading import get_model

[2019-02-27 20:29:09,473: INFO/ForkPoolWorker-1] Task celery_tasks.tasks.generate_static_index_html[b4dfbe88-8815-41a4-b150-e3cf9e3d6f24] succeeded in 0.3734534070827067s: None
[2019-02-27 20:31:32,657: INFO/MainProcess] Received task: celery_tasks.tasks.send_register_active_email[973fa7c0-4ba1-4843-a757-084a400fb0a1]  
[2019-02-27 20:31:35,450: INFO/ForkPoolWorker-1] Task celery_tasks.tasks.send_register_active_email[973fa7c0-4ba1-4843-a757-084a400fb0a1] succeeded in 2.7920797569677234s: None
[2019-02-27 21:11:53,386: INFO/MainProcess] Received task: celery_tasks.tasks.send_register_active_email[49eb0f23-1513-4183-a63a-3bd299fbcbac]  
[2019-02-27 21:11:55,436: INFO/ForkPoolWorker-1] Task celery_tasks.tasks.send_register_active_email[49eb0f23-1513-4183-a63a-3bd299fbcbac] succeeded in 2.0485571320168674s: None
[2019-02-27 21:25:27,100: INFO/MainProcess] Received task: celery_tasks.tasks.send_register_active_email[e7fa853b-3f75-4795-810d-64c260121c05]  
[2019-02-27 21:25:27,590: INFO/ForkPoolWorker-1] Task celery_tasks.tasks.send_register_active_email[e7fa853b-3f75-4795-810d-64c260121c05] succeeded in 0.48918749019503593s: None
[2019-02-27 21:27:40,831: INFO/MainProcess] Received task: celery_tasks.tasks.send_register_active_email[a3e50f76-d511-4ae3-86d2-6fbd1158b40c]  
[2019-02-27 21:27:43,576: INFO/ForkPoolWorker-1] Task celery_tasks.tasks.send_register_active_email[a3e50f76-d511-4ae3-86d2-6fbd1158b40c] succeeded in 2.7430866798385978s: None
[2019-02-27 21:29:00,134: INFO/MainProcess] Received task: celery_tasks.tasks.send_register_active_email[6903fbee-eaf2-400b-9f25-ba286b4c964e]  
[2019-02-27 21:29:00,561: INFO/ForkPoolWorker-1] Task celery_tasks.tasks.send_register_active_email[6903fbee-eaf2-400b-9f25-ba286b4c964e] succeeded in 0.4264216779265553s: None
[2019-02-27 21:29:38,064: INFO/MainProcess] Received task: celery_tasks.tasks.send_register_active_email[f4d6a3a5-1d30-451d-a8de-7042896e804c]  
[2019-02-27 21:29:38,556: INFO/ForkPoolWorker-1] Task celery_tasks.tasks.send_register_active_email[f4d6a3a5-1d30-451d-a8de-7042896e804c] succeeded in 0.4904653311241418s: None
[2019-02-27 21:40:23,468: INFO/MainProcess] Received task: celery_tasks.tasks.send_register_active_email[2d3f50e8-89c9-470d-bbcf-910f32a097a5]  
[2019-02-27 21:40:23,994: INFO/ForkPoolWorker-1] Task celery_tasks.tasks.send_register_active_email[2d3f50e8-89c9-470d-bbcf-910f32a097a5] succeeded in 0.5254868308547884s: None
[2019-02-28 14:02:37,369: INFO/MainProcess] Received task: celery_tasks.tasks.send_register_active_email[0a56cbe8-3365-4fda-99ed-c9b2ef0d33c0]  
[2019-02-28 14:02:40,080: INFO/ForkPoolWorker-1] Task celery_tasks.tasks.send_register_active_email[0a56cbe8-3365-4fda-99ed-c9b2ef0d33c0] succeeded in 2.693505304167047s: None
[2019-02-28 14:05:18,791: INFO/MainProcess] Received task: celery_tasks.tasks.send_register_active_email[c4e58cb0-986e-459c-a13b-29f7ef92936d]  
[2019-02-28 14:05:19,208: INFO/ForkPoolWorker-1] Task celery_tasks.tasks.send_register_active_email[c4e58cb0-986e-459c-a13b-29f7ef92936d] succeeded in 0.4163185330107808s: None
[2019-02-28 15:31:52,481: INFO/MainProcess] Received task: celery_tasks.tasks.send_register_active_email[a7cd2f75-f11f-40be-ac89-01f2a4220dd7]  
[2019-02-28 15:31:54,537: INFO/ForkPoolWorker-1] Task celery_tasks.tasks.send_register_active_email[a7cd2f75-f11f-40be-ac89-01f2a4220dd7] succeeded in 2.054949719225988s: None
[2019-02-28 19:48:12,866: CRITICAL/MainProcess] Unrecoverable error: ResponseError('MISCONF Redis is configured to save RDB snapshots, but is currently not able to persist on disk. Commands that may modify the data set are disabled. Please check Redis logs for details about the error.',)
Traceback (most recent call last):
  File "/home/ubuntu/.virtualenvs/django_py3/lib/python3.5/site-packages/celery/worker/worker.py", line 205, in start
    self.blueprint.start(self)
  File "/home/ubuntu/.virtualenvs/django_py3/lib/python3.5/site-packages/celery/bootsteps.py", line 119, in start
    step.start(parent)
  File "/home/ubuntu/.virtualenvs/django_py3/lib/python3.5/site-packages/celery/bootsteps.py", line 369, in start
    return self.obj.start()
  File "/home/ubuntu/.virtualenvs/django_py3/lib/python3.5/site-packages/celery/worker/consumer/consumer.py", line 317, in start
    blueprint.start(self)
  File "/home/ubuntu/.virtualenvs/django_py3/lib/python3.5/site-packages/celery/bootsteps.py", line 119, in start
    step.start(parent)
  File "/home/ubuntu/.virtualenvs/django_py3/lib/python3.5/site-packages/celery/worker/consumer/consumer.py", line 593, in start
    c.loop(*c.loop_args())
  File "/home/ubuntu/.virtualenvs/django_py3/lib/python3.5/site-packages/celery/worker/loops.py", line 91, in asynloop
    next(loop)
  File "/home/ubuntu/.virtualenvs/django_py3/lib/python3.5/site-packages/kombu/asynchronous/hub.py", line 354, in create_loop
    cb(*cbargs)
  File "/home/ubuntu/.virtualenvs/django_py3/lib/python3.5/site-packages/kombu/transport/redis.py", line 1047, in on_readable
    self.cycle.on_readable(fileno)
  File "/home/ubuntu/.virtualenvs/django_py3/lib/python3.5/site-packages/kombu/transport/redis.py", line 344, in on_readable
    chan.handlers[type]()
  File "/home/ubuntu/.virtualenvs/django_py3/lib/python3.5/site-packages/kombu/transport/redis.py", line 721, in _brpop_read
    **options)
  File "/home/ubuntu/.virtualenvs/django_py3/lib/python3.5/site-packages/redis/client.py", line 680, in parse_response
    response = connection.read_response()
  File "/home/ubuntu/.virtualenvs/django_py3/lib/python3.5/site-packages/redis/connection.py", line 629, in read_response
    raise response
redis.exceptions.ResponseError: MISCONF Redis is configured to save RDB snapshots, but is currently not able to persist on disk. Commands that may modify the data set are disabled. Please check Redis logs for details about the error.
[2019-03-30 14:02:02,031: INFO/MainProcess] Connected to redis://127.0.0.1:6379/8
[2019-03-30 14:02:02,039: INFO/MainProcess] mingle: searching for neighbors
[2019-03-30 14:02:03,058: INFO/MainProcess] mingle: all alone
[2019-03-30 14:02:03,066: INFO/MainProcess] w1@VM-0-11-ubuntu ready.
[2019-03-30 14:04:37,135: INFO/MainProcess] Received task: celery_tasks.tasks.send_register_active_email[efc24348-8df7-4022-8998-e00c87f8aaf4]  
[2019-03-30 14:04:38,339: INFO/ForkPoolWorker-1] Task celery_tasks.tasks.send_register_active_email[efc24348-8df7-4022-8998-e00c87f8aaf4] succeeded in 1.2017063540406525s: None
[2019-04-18 15:11:08,503: INFO/MainProcess] Received task: celery_tasks.tasks.send_register_active_email[cffda36f-3569-4dba-81a5-a493317ff98b]  
[2019-04-18 15:11:11,336: INFO/ForkPoolWorker-1] Task celery_tasks.tasks.send_register_active_email[cffda36f-3569-4dba-81a5-a493317ff98b] succeeded in 2.60616584867239s: None
[2019-04-18 15:16:49,954: INFO/MainProcess] Received task: celery_tasks.tasks.send_register_active_email[b78200d1-4a47-4d68-b01f-e43c8f99cd16]  
[2019-04-18 15:16:50,450: INFO/ForkPoolWorker-1] Task celery_tasks.tasks.send_register_active_email[b78200d1-4a47-4d68-b01f-e43c8f99cd16] succeeded in 0.49513402208685875s: None
[2019-04-18 15:17:24,062: INFO/MainProcess] Received task: celery_tasks.tasks.send_register_active_email[d59561f2-9f9e-455c-9334-044a4207fca7]  
[2019-04-18 15:17:24,553: INFO/ForkPoolWorker-1] Task celery_tasks.tasks.send_register_active_email[d59561f2-9f9e-455c-9334-044a4207fca7] succeeded in 0.490298792719841s: None
[2019-04-18 15:20:34,504: INFO/MainProcess] Received task: celery_tasks.tasks.send_register_active_email[d1f5b956-9eb3-490b-aadf-7a45c1e81fa8]  
[2019-04-18 15:20:34,974: INFO/ForkPoolWorker-1] Task celery_tasks.tasks.send_register_active_email[d1f5b956-9eb3-490b-aadf-7a45c1e81fa8] succeeded in 0.46906784269958735s: None
[2019-04-18 15:25:18,217: INFO/MainProcess] Received task: celery_tasks.tasks.send_register_active_email[4557acd6-922b-4b8f-9bf1-e273445b3149]  
[2019-04-18 15:25:18,655: INFO/ForkPoolWorker-1] Task celery_tasks.tasks.send_register_active_email[4557acd6-922b-4b8f-9bf1-e273445b3149] succeeded in 0.4371345806866884s: None
[2019-04-18 15:33:24,517: INFO/MainProcess] Received task: celery_tasks.tasks.send_register_active_email[f00c96d1-ed8f-4958-81e0-28c36de9baf3]  
[2019-04-18 15:33:27,449: INFO/ForkPoolWorker-1] Task celery_tasks.tasks.send_register_active_email[f00c96d1-ed8f-4958-81e0-28c36de9baf3] succeeded in 2.9303904930129647s: None
[2019-04-18 15:44:36,831: INFO/MainProcess] Received task: celery_tasks.tasks.send_register_active_email[d9027811-c0f7-4986-a63e-e7c20c5bc5ab]  
[2019-04-18 15:44:41,177: INFO/ForkPoolWorker-1] Task celery_tasks.tasks.send_register_active_email[d9027811-c0f7-4986-a63e-e7c20c5bc5ab] succeeded in 4.344576908275485s: None
[2019-04-18 15:45:08,378: INFO/MainProcess] Received task: celery_tasks.tasks.send_register_active_email[230334e9-49f2-46f9-b422-189e0e01f96a]  
[2019-04-18 15:45:09,464: INFO/ForkPoolWorker-1] Task celery_tasks.tasks.send_register_active_email[230334e9-49f2-46f9-b422-189e0e01f96a] succeeded in 1.084316979162395s: None
[2019-04-18 15:50:10,727: INFO/MainProcess] Received task: celery_tasks.tasks.send_register_active_email[7c44a761-3d1a-4238-8804-e26e16539b44]  
[2019-04-18 15:50:11,793: INFO/ForkPoolWorker-1] Task celery_tasks.tasks.send_register_active_email[7c44a761-3d1a-4238-8804-e26e16539b44] succeeded in 1.0520328804850578s: None
[2019-04-18 15:51:34,768: INFO/MainProcess] Received task: celery_tasks.tasks.send_register_active_email[476b0339-e380-47c0-ad71-2cde845dbe1c]  
[2019-04-18 15:51:35,782: INFO/ForkPoolWorker-1] Task celery_tasks.tasks.send_register_active_email[476b0339-e380-47c0-ad71-2cde845dbe1c] succeeded in 1.0135775161907077s: None
[2019-04-18 16:01:03,491: INFO/MainProcess] Received task: celery_tasks.tasks.send_register_active_email[b220dd85-0441-45b8-bf9e-2d8bef3d7189]  
[2019-04-18 16:01:05,684: INFO/ForkPoolWorker-1] Task celery_tasks.tasks.send_register_active_email[b220dd85-0441-45b8-bf9e-2d8bef3d7189] succeeded in 2.1925622038543224s: None
[2019-04-18 16:12:54,999: INFO/MainProcess] Received task: celery_tasks.tasks.send_register_active_email[16db1201-309c-45c7-9751-4cacc9be6e58]  
[2019-04-18 16:12:59,551: INFO/ForkPoolWorker-1] Task celery_tasks.tasks.send_register_active_email[16db1201-309c-45c7-9751-4cacc9be6e58] succeeded in 4.5508757550269365s: None
[2019-04-18 16:13:50,433: INFO/MainProcess] Received task: celery_tasks.tasks.send_register_active_email[77b53f45-9d41-4315-9f11-aa62843d0505]  
[2019-04-18 16:13:51,408: INFO/ForkPoolWorker-1] Task celery_tasks.tasks.send_register_active_email[77b53f45-9d41-4315-9f11-aa62843d0505] succeeded in 0.9745389698073268s: None
[2019-04-18 16:19:45,728: INFO/MainProcess] Received task: celery_tasks.tasks.send_register_active_email[8fe1c615-82d9-4605-a697-1859e4901ea7]  
[2019-04-18 16:19:46,161: INFO/ForkPoolWorker-1] Task celery_tasks.tasks.send_register_active_email[8fe1c615-82d9-4605-a697-1859e4901ea7] succeeded in 0.4318336024880409s: None
[2019-04-18 16:20:28,057: INFO/MainProcess] Received task: celery_tasks.tasks.send_register_active_email[b0943d7e-61bb-40d6-bca3-344f7bff5352]  
[2019-04-18 16:20:28,507: INFO/ForkPoolWorker-1] Task celery_tasks.tasks.send_register_active_email[b0943d7e-61bb-40d6-bca3-344f7bff5352] succeeded in 0.449508436024189s: None
[2019-04-19 19:04:29,271: INFO/MainProcess] Received task: celery_tasks.tasks.generate_static_index_html[3a67f69f-1485-4769-a6a8-28b7b2462c77]  
[2019-04-19 19:04:29,373: WARNING/ForkPoolWorker-1] /home/ubuntu/.virtualenvs/django_py3/lib/python3.5/site-packages/haystack/backends/whoosh_cn_backend.py:9: RemovedInDjango19Warning: The utilities in django.db.models.loading are deprecated in favor of the new application loading system.
  from django.db.models.loading import get_model

[2019-04-19 19:04:29,806: INFO/ForkPoolWorker-1] Task celery_tasks.tasks.generate_static_index_html[3a67f69f-1485-4769-a6a8-28b7b2462c77] succeeded in 0.5336950598284602s: None
